### PR TITLE
Update Weekend Caps and Senior Fares

### PR DESCRIPTION
**Pull request by Testsr**
https://www.ptv.vic.gov.au/tickets/fares/metropolitan-fares/ 
The fares are updated. I live in Melbourne as well.

### CODE REVIEW

**Comment by Testsr** [comment]
Sorry.

**Comment by Testsr** [comment]
Do you want me to revert it?

**Comment by longzheng** [comment]
Nah, I was pleasantly surprised you even caught it 🤣

**Comment by Testsr** [comment]
Anything else? Do you want to merge it?

**Pull request merged**
